name: 'xluve-test #1'
favicon: null
layout_spectrum: 0.12750522117130458
typography_spectrum: 0.85317
title: 'How cool is the Beta Test #1'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6086961429100484
  lightness: 0.125
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
